---
Title: "Shark Microplastics"
Author: "Morgan Lattomus"
Date: "2/15/2022"
Output: 
  html_document: default
  pdf_document: default
  word_document: default
---
```{r upload data.csv}
shark_data <- read.csv('shark_data2.csv')
# uploading the data! 
```

```{r organizing sacrifice ids and id numbers to set up a merge}
library(dplyr)
uni_id <- paste(shark_data$Sacrifice.ID, shark_data$ID.., sep ='-')
uni_id
unique(uni_id)
unique(uni_id)[-2]
uni_id_full <- rep(unique(uni_id)[-2], each =4 )

shark_data$CommonName <- factor(shark_data$CommonName,
                                levels = c('finetooth', 'sharpnose', 'blacktip',
                                           'hammer head'))

#I am not entirely sure that this is needed anymore, but maybe check on that before deleted it!!
```


```{r stomach boxplot and figuring out significance}
library(ggplot2)

boxplot(Total ~ CommonName, data = shark_data, subset = Sample.Type=='S',
        xlab='Species', ylab='# of MPs')

mtext("Microplastics Found in Stomachs", side = 3, line = -2, outer = TRUE , font = 2)

sp_mod1 <- glm(Total ~ CommonName, data = shark_data, subset = Sample.Type=='S',
              family = 'poisson')
summary(sp_mod1)
# estimate psuedo r2
pseudo_r2 = function(glm_mod) {
    1 -  glm_mod$deviance / glm_mod$null.deviance
}

pseudo_r2(sp_mod1)
car::Anova(sp_mod1)
# literally no significance...it is SUCH small numbers on this omg
```

```{r spiral valve boxplot and figuring out v signifiance}

boxplot(Total ~ CommonName, data = shark_data, subset = Sample.Type=='V',
        xlab='Species', ylab='# of MPs')
#plotting the valve data
mtext("Microplastics Found in Spiral Valves", side = 3, line = -2, outer = TRUE , font = 2)

sp_mod <- glm(Total ~ CommonName, data = shark_data, subset = Sample.Type=='V',
              family = 'poisson')
summary(sp_mod)
# estimate psuedo r2
pseudo_r2 = function(glm_mod) {
    1 -  glm_mod$deviance / glm_mod$null.deviance
}

pseudo_r2(sp_mod)
car::Anova(sp_mod)
#some significance...6% of data is due to differences in species
```

```{r graphing avg totals per species}
combt <- shark_data$Total[shark_data$Sample.Type=='V'] + shark_data$Total[shark_data$Sample.Type== 'S']
#combining the valve and stomach totals to get a combined total

#attempting to make a boxplot and it's not going as well as I would like to...
boxplot(combt ~ CommonName[shark_data$Sample.Type== 'S'], data = shark_data,
        xlab='Species', ylab='# of MPs')

mtext("Total Microplastics Found per Shark", side = 3, line = -2, outer = TRUE , font = 2)

sp_mod3 <- glm(combt ~ CommonName[shark_data$Sample.Type== 'S'], data = shark_data, family = 'poisson')

pseudo_r2 = function(glm_mod) {
    1 -  glm_mod$deviance / glm_mod$null.deviance
}

pseudo_r2(sp_mod3)
car::Anova(sp_mod3)

```

```{r graphing totals per gram of fresh weight and significance}
pfw <- combt/shark_data$FW..g.[shark_data$Sample.Type== 'S']

boxplot(pfw ~ CommonName[shark_data$Sample.Type== 'S'], data = shark_data,
        xlab='Species', ylab='# of MPs')

mtext("Total Microplastics Found per g FW", side = 3, line = -2, outer = TRUE , font = 2)

sp_mod4 <- glm(pfw ~ CommonName[shark_data$Sample.Type== 'S'], data = shark_data, family = 'poisson')

pseudo_r2 = function(glm_mod) {
    1 -  glm_mod$deviance / glm_mod$null.deviance
}

pseudo_r2(sp_mod4)
car::Anova(sp_mod4)
```



